<?php

/**
 * @file
 * Module file for Go to Comments
 */
 
/**
 * Implements hook_preprocess_page().
 *
 * Add the block to all the pages with comments.
 *
 * @param array $variables
 *   Preprocess variables array.
 */
function gotocomments_preprocess_page(&$variables) {
  if (isset($variables['node']) && $variables['node']->comment == 2) {
    $path = drupal_get_path('module', 'gotocomments');
    drupal_add_js($path . '/gotocomments.js');
    $settings = array(
      'gotocomments' => array(
        'comment_count' => $variables['node']->comment_count,
      ),
    );
    drupal_add_js($settings, 'setting');
    $variables['scripts'] = drupal_get_js();
    drupal_add_css($path . '/gotocomments.css');
    $variables['styles'] = drupal_get_css();
  }
}
